# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

approxExtrap_rcpp <- function(x, y, xout) {
    .Call(`_fcfdr_approxExtrap_rcpp`, x, y, xout)
}

#' @title Linear interpolation function
#'
#' @description This function carries out linear interpolation, reproducing a subset of the behaviour of stats::approx in R.
#'
#' @details Linear interpolation is performed with f(x)=f(x0)+[(f(x1)-f(x0))/(x1-x0)]*(x-x0). x is assumed to be sorted; if sorted in descending order, the order of elements in x and y is reversed. If a value of xout lies outside the range [min(x), max(x)], the value is interpolated using the nearest extremum (this corresponds to the behaviour of stats::approx with method=2).
#'
#' @param x x coordinates of points to be interpolated
#' @param y y coordinates of points to be interpolated
#' @param xout x coordiantes at which to interpolate
#'
#' @return interpolated values 
#' 
#' @author Tom Willis
approxfun_rcpp <- function(x, y, xout) {
    .Call(`_fcfdr_approxfun_rcpp`, x, y, xout)
}

per_group_binary_cfdr <- function(p_loo, q_loo, ps, qs, x) {
    .Call(`_fcfdr_per_group_binary_cfdr`, p_loo, q_loo, ps, qs, x)
}

